#!/bin/bash

# Exercise 1
echo "This script will exit with a 0 exit status."
exit 0

# Exercise 2
if [[ -f $1 ]]; then
	exit 0
elif [[ -d $1 ]]; then
	exit 1
else
	exit 2
fi

# Exercise 3

if cat /etc/shadow; then
	echo "Commands succeeded."
else
	echo "Commands failed."
fi
